version: '3'

services:
  db:
    image: postgres
    ports:
      - 127.0.0.1:5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: test
  redis:
    image: redis
    ports:
      - 127.0.0.1:6379:6379
